version: '3.1'

services: 
    backend:
        image: maven:3.8.1-jdk-11
        command: mvn spring-boot:run
        ports:
            - 8080:8080
        volumes:
            - ./backend:/usr/src/app:rw
            - maven-repository:/root/.m2
        working_dir: /usr/src/app
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/spring
            - SPRING_DATASOURCE_USERNAME=user
            - SPRING_DATASOURCE_PASSWORD=user
            - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
        depends_on:
            - db
    
    db:
        image: postgres:13.3-alpine
        restart: always
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user
            POSTGRES_DB: spring


volumes:
    maven-repository: